<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AnggotaSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('anggota')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        $chunks = array_chunk($this->data(), 50);
        foreach ($chunks as $chunk) {
            DB::table('anggota')->insert($chunk);
        }
    }

    private function data(): array
    {
        return [
        [
            'id_anggota' => 1,
            'nama' => 'Muhammad Nur , SP., M.Si',
            'no_anggota' => 'KSA_001',
            'email' => 'ksa001@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 2,
            'nama' => 'Junaidin, S.Pd., M.Pd',
            'no_anggota' => 'KSA_002',
            'email' => 'ksa002@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 3,
            'nama' => 'Dr. Sabaruddin Sondeng, SE., M.Si',
            'no_anggota' => 'KSA_003',
            'email' => 'ksa003@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 4,
            'nama' => 'Asriani , SP., M.Sc',
            'no_anggota' => 'KSA_004',
            'email' => 'ksa004@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 5,
            'nama' => 'Eddy Hamka, S.Pi., M.Si',
            'no_anggota' => 'KSA_005',
            'email' => 'ksa005@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => 'L',
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 6,
            'nama' => 'Dr. Fajriah, S.Pi., M.Si',
            'no_anggota' => 'KSA_007',
            'email' => 'ksa007@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 7,
            'nama' => 'Dr. Syamsinar, SP., M.Si',
            'no_anggota' => 'KSA_008',
            'email' => 'ksa008@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 8,
            'nama' => 'Dra Mujiati, M.Si',
            'no_anggota' => 'KSA_011',
            'email' => 'ksa011@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 9,
            'nama' => 'Dr. Basri Sufa, S.Kom., MP',
            'no_anggota' => 'KSA_012',
            'email' => 'ksa012@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 10,
            'nama' => 'Syamsul Anam, SE., M.Ec Dev',
            'no_anggota' => 'KSA_013',
            'email' => 'ksa013@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 11,
            'nama' => 'Dr. Sitti Rosmalah, SP., MP',
            'no_anggota' => 'KSA_014',
            'email' => 'ksa014@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 12,
            'nama' => 'Dr. Sitti Zakiah Ma’mun, SE., M.Si',
            'no_anggota' => 'KSA_015',
            'email' => 'ksa015@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 13,
            'nama' => 'Patta Hindi Asis, S.Sos., MA',
            'no_anggota' => 'KSA_016',
            'email' => 'ksa016@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 14,
            'nama' => 'Andi Awaluddin Maruf, S.IP., M.Si',
            'no_anggota' => 'KSA_017',
            'email' => 'ksa017@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 15,
            'nama' => 'Mualif Arsyad, SKM., M.Epid',
            'no_anggota' => 'KSA_019',
            'email' => 'ksa019@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 16,
            'nama' => 'Ahmad, S.Pd.I',
            'no_anggota' => 'KSA_020',
            'email' => 'ksa020@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 17,
            'nama' => 'Afdal Nur, SP',
            'no_anggota' => 'KSA_021',
            'email' => 'ksa021@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 18,
            'nama' => 'Ary Tamtama, S.Pi., M.Pi',
            'no_anggota' => 'KSA_022',
            'email' => 'ksa022@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 19,
            'nama' => 'Jumiatin, S.Pd., M.Pd',
            'no_anggota' => 'KSA_023',
            'email' => 'ksa023@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 20,
            'nama' => 'Juwita, SE.Sy., MM',
            'no_anggota' => 'KSA_024',
            'email' => 'ksa024@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 21,
            'nama' => 'Sitti Hikmawaty Sahiddin, S. Pd',
            'no_anggota' => 'KSA_025',
            'email' => 'ksa025@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 22,
            'nama' => 'Ervina Ayuni',
            'no_anggota' => 'KSA_026',
            'email' => 'ksa026@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 23,
            'nama' => 'Mariani, SE., ME',
            'no_anggota' => 'KSA_027',
            'email' => 'ksa027@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 24,
            'nama' => 'Adi Firamayana, SH., MH',
            'no_anggota' => 'KSA_028',
            'email' => 'ksa028@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 25,
            'nama' => 'Tri Indah Rusli, S.Pd., M.Pd',
            'no_anggota' => 'KSA_029',
            'email' => 'ksa029@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 26,
            'nama' => 'Faisal Abdaud , SH., MH',
            'no_anggota' => 'KSA_030',
            'email' => 'ksa030@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 27,
            'nama' => 'Anwar Said, S.Si., M.Pd',
            'no_anggota' => 'KSA_031',
            'email' => 'ksa031@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 28,
            'nama' => 'Muhlasin, SH., MH',
            'no_anggota' => 'KSA_032',
            'email' => 'ksa032@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 29,
            'nama' => 'Dr. Ahmad Muhlis Nuryadi, S.Pi.,M.Si',
            'no_anggota' => 'KSA_033',
            'email' => 'ksa033@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 30,
            'nama' => 'Dr. Hj. Hartati, S.P., M.Si',
            'no_anggota' => 'KSA_034',
            'email' => 'ksa034@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 31,
            'nama' => 'Zulaeni Esita, S.Psi., MA',
            'no_anggota' => 'KSA_037',
            'email' => 'ksa037@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 32,
            'nama' => 'Apriani Safitri, S.Pd., M.Pd',
            'no_anggota' => 'KSA_039',
            'email' => 'ksa039@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 33,
            'nama' => 'Rita L Bubun, S.Pi., M.Si',
            'no_anggota' => 'KSA_040',
            'email' => 'ksa040@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 34,
            'nama' => 'Yudhi Dwi Hartono, ST., M.Sc',
            'no_anggota' => 'KSA_041',
            'email' => 'ksa041@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 35,
            'nama' => 'Wahyudin, S.Ip., M.Si',
            'no_anggota' => 'KSA_042',
            'email' => 'ksa042@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 36,
            'nama' => 'Musdalifah Tamin, S.Si., M.Pd',
            'no_anggota' => 'KSA_043',
            'email' => 'ksa043@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 37,
            'nama' => 'Kamaruddin , SH., MH',
            'no_anggota' => 'KSA_044',
            'email' => 'ksa044@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 38,
            'nama' => 'Zahirudin, S.Pi',
            'no_anggota' => 'KSA_045',
            'email' => 'ksa045@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 39,
            'nama' => 'Alwas Muis, S.Pd',
            'no_anggota' => 'KSA_047',
            'email' => 'ksa047@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 40,
            'nama' => 'Nining Sartikawati, SE',
            'no_anggota' => 'KSA_048',
            'email' => 'ksa048@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 41,
            'nama' => 'Nurhidayat, S.Pd',
            'no_anggota' => 'KSA_049',
            'email' => 'ksa049@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 42,
            'nama' => 'Titin Rahmiatin, S.Pd., M.Pd',
            'no_anggota' => 'KSA_050',
            'email' => 'ksa050@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 43,
            'nama' => 'Sahid, A Md.Kom',
            'no_anggota' => 'KSA_051',
            'email' => 'ksa051@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 44,
            'nama' => 'Fharanita Muhita, S.Pd',
            'no_anggota' => 'KSA_052',
            'email' => 'ksa052@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 45,
            'nama' => 'Halima, S.Ag., M.Pd',
            'no_anggota' => 'KSA_053',
            'email' => 'ksa053@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 46,
            'nama' => 'Marliana, S.Pd',
            'no_anggota' => 'KSA_054',
            'email' => 'ksa054@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 47,
            'nama' => 'Wa Embe, SP., M.Sc',
            'no_anggota' => 'KSA_055',
            'email' => 'ksa055@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 48,
            'nama' => 'Rosdiana, S.Pd., M.Si',
            'no_anggota' => 'KSA_056',
            'email' => 'ksa056@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 49,
            'nama' => 'A M Indra Suprianto, S.Ars',
            'no_anggota' => 'KSA_057',
            'email' => 'ksa057@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 50,
            'nama' => 'Mayasari, S.Sos., M.Si',
            'no_anggota' => 'KSA_058',
            'email' => 'ksa058@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 51,
            'nama' => 'La Ode Abdul Harlan, S.IP., M.Si',
            'no_anggota' => 'KSA_059',
            'email' => 'ksa059@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 52,
            'nama' => 'Wa Ode Hartini, SE',
            'no_anggota' => 'KSA_060',
            'email' => 'ksa060@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 53,
            'nama' => 'Sarmansyah Arifin, SE',
            'no_anggota' => 'KSA_061',
            'email' => 'ksa061@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 54,
            'nama' => 'Emir, S.Ip., M.Ap',
            'no_anggota' => 'KSA_062',
            'email' => 'ksa062@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 55,
            'nama' => 'Sudarto, S.Pd., M.Pd',
            'no_anggota' => 'KSA_063',
            'email' => 'ksa063@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 56,
            'nama' => 'Muallimah, S.Pd.I., M.Ag',
            'no_anggota' => 'KSA_064',
            'email' => 'ksa064@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 57,
            'nama' => 'Sutiati, S.Pd.i., M.Ag',
            'no_anggota' => 'KSA_065',
            'email' => 'ksa065@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 58,
            'nama' => 'Ilyas',
            'no_anggota' => 'KSA_066',
            'email' => 'ksa066@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 59,
            'nama' => 'Laode Rahmat Hidayat',
            'no_anggota' => 'KSA_067',
            'email' => 'ksa067@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 60,
            'nama' => 'Rahayu Kojongian, SH., MH',
            'no_anggota' => 'KSA_068',
            'email' => 'ksa068@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 61,
            'nama' => 'Hariman Satria Samansi, SH., LLM',
            'no_anggota' => 'KSA_069',
            'email' => 'ksa069@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 62,
            'nama' => 'Laode Lohor Kaea',
            'no_anggota' => 'KSA_071',
            'email' => 'ksa071@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 63,
            'nama' => 'Laode Kaisar',
            'no_anggota' => 'KSA_072',
            'email' => 'ksa072@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 64,
            'nama' => 'Sabar Novriadi',
            'no_anggota' => 'KSA_075',
            'email' => 'ksa075@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 65,
            'nama' => 'Muhammad Nur Djafar Sigaro, S.IK',
            'no_anggota' => 'KSA_077',
            'email' => 'ksa077@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 66,
            'nama' => 'Dedi darisno, S.IP',
            'no_anggota' => 'KSA_078',
            'email' => 'ksa078@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 67,
            'nama' => 'Jamiruddin',
            'no_anggota' => 'KSA_079',
            'email' => 'ksa079@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 68,
            'nama' => 'Nur Nashrum Jufri, SE., M.Si',
            'no_anggota' => 'KSA_080',
            'email' => 'ksa080@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 69,
            'nama' => 'Budi Setiawan, SE',
            'no_anggota' => 'KSA_081',
            'email' => 'ksa081@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 70,
            'nama' => 'Hendra Nelva Saputra, S.Pd., M.Pd',
            'no_anggota' => 'KSA_082',
            'email' => 'ksa082@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 71,
            'nama' => 'Rahmahayati, SE',
            'no_anggota' => 'KSA_083',
            'email' => 'ksa083@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 72,
            'nama' => 'Baharuddin',
            'no_anggota' => 'KSA_084',
            'email' => 'ksa084@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 73,
            'nama' => 'Nur Rizky Alfiany Suaib, SS., M.Hum',
            'no_anggota' => 'KSA_085',
            'email' => 'ksa085@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 74,
            'nama' => 'Atriani Abbas, S,Pd',
            'no_anggota' => 'KSA_086',
            'email' => 'ksa086@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 75,
            'nama' => 'Lely Okmawaty Anwar, S.Pi., M.Si',
            'no_anggota' => 'KSA_087',
            'email' => 'ksa087@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 76,
            'nama' => 'Abdul Rahman',
            'no_anggota' => 'KSA_088',
            'email' => 'ksa088@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 77,
            'nama' => 'Muh Akbar Fitrahyanto',
            'no_anggota' => 'KSA_089',
            'email' => 'ksa089@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 78,
            'nama' => 'Madinatul Ilmi',
            'no_anggota' => 'KSA_090',
            'email' => 'ksa090@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 79,
            'nama' => 'Wa Ode Kaene',
            'no_anggota' => 'KSA_091',
            'email' => 'ksa091@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 80,
            'nama' => 'Muh Ilyas',
            'no_anggota' => 'KSA_092',
            'email' => 'ksa092@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 81,
            'nama' => 'Muftihaturrahmah',
            'no_anggota' => 'KSA_093',
            'email' => 'ksa093@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 82,
            'nama' => 'Dian Putery Nurbaity',
            'no_anggota' => 'KSA_094',
            'email' => 'ksa094@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 83,
            'nama' => 'Zaldhy Priady Sao sao',
            'no_anggota' => 'KSA_095',
            'email' => 'ksa095@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 84,
            'nama' => 'Wa Ndibale',
            'no_anggota' => 'KSA_096',
            'email' => 'ksa096@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 85,
            'nama' => 'Irwansyah',
            'no_anggota' => 'KSA_097',
            'email' => 'ksa097@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 86,
            'nama' => 'La Ode Fahasini',
            'no_anggota' => 'KSA_098',
            'email' => 'ksa098@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 87,
            'nama' => 'Mustam',
            'no_anggota' => 'KSA_099',
            'email' => 'ksa099@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 88,
            'nama' => 'Dwi Prayogo Wibowo',
            'no_anggota' => 'KSA_100',
            'email' => 'ksa100@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 89,
            'nama' => 'Lasiah Ragil',
            'no_anggota' => 'KSA_101',
            'email' => 'ksa101@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 90,
            'nama' => 'Saimudin',
            'no_anggota' => 'KSA_102',
            'email' => 'ksa102@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 91,
            'nama' => 'Milawati',
            'no_anggota' => 'KSA_103',
            'email' => 'ksa103@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 92,
            'nama' => 'Hasmira Said',
            'no_anggota' => 'KSA_104',
            'email' => 'ksa104@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 93,
            'nama' => 'La Ode Ali Musa',
            'no_anggota' => 'KSA_105',
            'email' => 'ksa105@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 94,
            'nama' => 'Nurul idhayani',
            'no_anggota' => 'KSA_106',
            'email' => 'ksa106@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 95,
            'nama' => 'Hadijah Selman',
            'no_anggota' => 'KSA_107',
            'email' => 'ksa107@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 96,
            'nama' => 'Abriansyah',
            'no_anggota' => 'KSA_108',
            'email' => 'ksa108@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 97,
            'nama' => 'Ratna Bachrun',
            'no_anggota' => 'KSA_109',
            'email' => 'ksa109@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 98,
            'nama' => 'Al Amin Siharis',
            'no_anggota' => 'KSA_110',
            'email' => 'ksa110@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 99,
            'nama' => 'Arfin',
            'no_anggota' => 'KSA_111',
            'email' => 'ksa111@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 100,
            'nama' => 'Asdin',
            'no_anggota' => 'KSA_112',
            'email' => 'ksa112@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 101,
            'nama' => 'Muh Alamsyah',
            'no_anggota' => 'KSA_113',
            'email' => 'ksa113@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 102,
            'nama' => 'Mochammad Assidieq',
            'no_anggota' => 'KSA_114',
            'email' => 'ksa114@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 103,
            'nama' => 'Surya Baskara',
            'no_anggota' => 'KSA_115',
            'email' => 'ksa115@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 104,
            'nama' => 'Muh Rizky Fauzan',
            'no_anggota' => 'KSA_116',
            'email' => 'ksa116@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 105,
            'nama' => 'Rafly',
            'no_anggota' => 'KSA_117',
            'email' => 'ksa117@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 106,
            'nama' => 'Sukadi',
            'no_anggota' => 'KSA_118',
            'email' => 'ksa118@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 107,
            'nama' => 'Annajar Madjani Tahir',
            'no_anggota' => 'KSA_119',
            'email' => 'ksa119@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 108,
            'nama' => 'Wd Kurnia',
            'no_anggota' => 'KSA_120',
            'email' => 'ksa120@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 109,
            'nama' => 'Wd. Taati',
            'no_anggota' => 'KSA_121',
            'email' => 'ksa121@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 110,
            'nama' => 'Hasrawati',
            'no_anggota' => 'KSA_122',
            'email' => 'ksa122@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 111,
            'nama' => 'Nani',
            'no_anggota' => 'KSA_123',
            'email' => 'ksa123@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 112,
            'nama' => 'Rosmawati',
            'no_anggota' => 'KSA_124',
            'email' => 'ksa124@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 113,
            'nama' => 'Suarni Ambotuo',
            'no_anggota' => 'KSA_125',
            'email' => 'ksa125@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 114,
            'nama' => 'Dian Sri Wahyuni',
            'no_anggota' => 'KSA_126',
            'email' => 'ksa126@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 115,
            'nama' => 'Rey Nilda',
            'no_anggota' => 'KSA_127',
            'email' => 'ksa127@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 116,
            'nama' => 'Darman, S.Pd., M.Pd',
            'no_anggota' => 'KSA_128',
            'email' => 'ksa128@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 117,
            'nama' => 'Izra Danuharja',
            'no_anggota' => 'KSA_129',
            'email' => 'ksa129@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 118,
            'nama' => 'Arlan',
            'no_anggota' => 'KSA_130',
            'email' => 'ksa130@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 119,
            'nama' => 'Atmaja',
            'no_anggota' => 'KSA_131',
            'email' => 'ksa131@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 120,
            'nama' => 'Darlin',
            'no_anggota' => 'KSA_132',
            'email' => 'ksa132@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 121,
            'nama' => 'Agus Tamin',
            'no_anggota' => 'KSA_133',
            'email' => 'ksa133@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 122,
            'nama' => 'Mulyani Mustamin',
            'no_anggota' => 'KSA_134',
            'email' => 'ksa134@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 123,
            'nama' => 'Andi Syaiful',
            'no_anggota' => 'KSA_135',
            'email' => 'ksa135@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 124,
            'nama' => 'Nurzaima',
            'no_anggota' => 'KSA_136',
            'email' => 'ksa136@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 125,
            'nama' => 'Muh Fadhil Hidayat',
            'no_anggota' => 'KSA_137',
            'email' => 'ksa137@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 126,
            'nama' => 'Rohmiati',
            'no_anggota' => 'KSA_138',
            'email' => 'ksa138@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 127,
            'nama' => 'Zila Razilu',
            'no_anggota' => 'KSA_139',
            'email' => 'ksa139@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 128,
            'nama' => 'Fitriani',
            'no_anggota' => 'KSA_141',
            'email' => 'ksa141@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 129,
            'nama' => 'Nujuludin',
            'no_anggota' => 'KSA_142',
            'email' => 'ksa142@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 130,
            'nama' => 'Yunita Eka Pratiwi',
            'no_anggota' => 'KSA_143',
            'email' => 'ksa143@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 131,
            'nama' => 'Awardin',
            'no_anggota' => 'KSA_144',
            'email' => 'ksa144@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 132,
            'nama' => 'Yusdin',
            'no_anggota' => 'KSA_145',
            'email' => 'ksa145@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 133,
            'nama' => 'Wa Sila',
            'no_anggota' => 'KSA_146',
            'email' => 'ksa146@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 134,
            'nama' => 'Citra Lawati',
            'no_anggota' => 'KSA_147',
            'email' => 'ksa147@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 135,
            'nama' => 'Wa Eni',
            'no_anggota' => 'KSA_148',
            'email' => 'ksa148@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 136,
            'nama' => 'Nahdatunnisa',
            'no_anggota' => 'KSA_149',
            'email' => 'ksa149@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 137,
            'nama' => 'Nurul Aisyah Abibah',
            'no_anggota' => 'KSA_150',
            'email' => 'ksa150@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 138,
            'nama' => 'Ismi Fadjriah Hamzah',
            'no_anggota' => 'KSA_151',
            'email' => 'ksa151@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 139,
            'nama' => 'Rini Puji Astuti',
            'no_anggota' => 'KSA_152',
            'email' => 'ksa152@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 140,
            'nama' => 'Wa Ode Suri',
            'no_anggota' => 'KSA_153',
            'email' => 'ksa153@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 141,
            'nama' => 'Faridawati',
            'no_anggota' => 'KSA_154',
            'email' => 'ksa154@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 142,
            'nama' => 'Gamlan Dagani',
            'no_anggota' => 'KSA_155',
            'email' => 'ksa155@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 143,
            'nama' => 'Selvi Diliyanti rizky',
            'no_anggota' => 'KSA_156',
            'email' => 'ksa156@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 144,
            'nama' => 'Muammar',
            'no_anggota' => 'KSA_157',
            'email' => 'ksa157@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 145,
            'nama' => 'Wa Ode Hamnasia',
            'no_anggota' => 'KSA_158',
            'email' => 'ksa158@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 146,
            'nama' => 'Herawati',
            'no_anggota' => 'KSA_159',
            'email' => 'ksa159@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 147,
            'nama' => 'La Teke',
            'no_anggota' => 'KSA_160',
            'email' => 'ksa160@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 148,
            'nama' => 'Dirawati (FH)',
            'no_anggota' => 'KSA_161',
            'email' => 'ksa161@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 149,
            'nama' => 'Selvi Abas, S.Pd. (PAI)',
            'no_anggota' => 'KSA_162',
            'email' => 'ksa162@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 150,
            'nama' => 'Atil Mizatun (Rektorat)',
            'no_anggota' => 'KSA_163',
            'email' => 'ksa163@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 151,
            'nama' => 'Desi Rahmawati (FT)',
            'no_anggota' => 'KSA_164',
            'email' => 'ksa164@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 152,
            'nama' => 'Dr. Yusuf, S.Pd.I., M.Pd.I. (PAI)',
            'no_anggota' => 'KSA_165',
            'email' => 'ksa165@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 153,
            'nama' => 'Muhammad Dikman Maheng (FT)',
            'no_anggota' => 'KSA_166',
            'email' => 'ksa166@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 154,
            'nama' => 'Aruwiah (DSD)',
            'no_anggota' => 'KSA_167',
            'email' => 'ksa167@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 155,
            'nama' => 'Ma\'ruf Akib (FH)',
            'no_anggota' => 'KSA_168',
            'email' => 'ksa168@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 156,
            'nama' => 'Muh. Ihsan Mattalitti (FISIP)',
            'no_anggota' => 'KSA_169',
            'email' => 'ksa169@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 157,
            'nama' => 'Sri Santi Dharma Sumarsi (FPIK)',
            'no_anggota' => 'KSA_170',
            'email' => 'ksa170@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 158,
            'nama' => 'Multi Sri Asnani (FH)',
            'no_anggota' => 'KSA_171',
            'email' => 'ksa171@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        [
            'id_anggota' => 159,
            'nama' => 'Nur Halipa (DPAH)',
            'no_anggota' => 'KSA_172',
            'email' => 'ksa172@umkendari.ac.id',
            'alamat' => NULL,
            'tempat_lahir' => NULL,
            'tanggal_lahir' => NULL,
            'jenis_kelamin' => NULL,
            'pekerjaan' => NULL,
            'id_status_anggota' => 1,
            'aktif' => 'Y',
            'created_at' => '2026-04-18 10:01:19',
            'updated_at' => '2026-04-18 10:01:19',
        ],
        ];
    }
}
